sudo: false
language: node_js
node_js:
- 'stable'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - /^greenkeeper-.*$/
notifications:
  email: false
before_script:
- npm prune
script:
- npm run build
after_script:
- bash ./scripts/deploy.sh
env:
  global:
  - GH_USER: voorhoede
  - GH_REPO: fastatic
  - secure: d6gnAXENj2vJ5/cvGUoxk6MNsVKVYU0cdx+7NTmw67cW0Ek+nW3z1ILW36gV8WNcuitQwJmlJC1LK8FjHiS0LjWT2sX+uQ2XojHQJR30DwApbltj2QV3No/A7BqYNn5M4CD8SUucJK1tNxYB09EvdcbYfo8kb0aKpe0PYXAHWGCCixOyOgRcsSX80BaPCl4lpWYPGOiGk8fXykfsnjBsctu+VKdya0iTVq+3ucBSx/l+4l2Ncr4guT2z4NNpfDUgARtEKgyVBHShjw5HnhMEVzjNtDsXdEFvY/eCxch/aDixLhAxefZbhaqU1OH6I0GhrwAe7jemzvhinHuK4OqTa58IpS4XTntLLR/Zo1j7cQXMTqs/STjPxGrnjp0bZHoBQOjHPIOwCGe1RLs393SxveoqpaQ/36Zv/R7Zic6uvMpqxDeccTMwuZObKfQmjXO4u2+FlsM6aVzJd/36Fb5it/qo2MA8e4epUtiOrB4nJGCiVjzyPCnBCB2eWe+23HRq6GycahwcvsWx6z1BUiBjPQoux/bgH7MtJfN02LnshNFciNiJPMNyS5GfXB9H6KcBKzWv+g77JYrTR+wQVTUbKO4QY1qGO2NMXgKksFT1JAfd+AKPRyMQ7gfWBNp0K4MocHv2dbqEDxtG90sLcFoSaYh2S8vEWDHhJpsq/8jfmNQ=
